### ISSUE TITLE
JSLint doesn't like new

### ISSUE THREAD

**Issue by PsySecCorp** [mstg/metadisk.js#1]
https://github.com/mstg/metadisk.js/blob/master/lib/index.js#L27
https://github.com/mstg/metadisk.js/blob/dcd9bcb1c3ad41e9caafed35c15ed1fdcaf301ac/examples/new.js#L3
https://github.com/mstg/metadisk.js/blob/dcd9bcb1c3ad41e9caafed35c15ed1fdcaf301ac/examples/balance.js#L4
https://github.com/mstg/metadisk.js/blob/b820d7f7b4d785742a29a08c99b83f93d9a7eeb3/README.md#L37

Perhaps use `create` instead of `new`?  Currently using `metadisk.accounts.token['new']()` to get around it.

**Comment by mstg** [comment]
Fixed in faf594dbd4a499a8ee750f2585d77e5b9b6fdf88
